model:
  arch: florence2_vqa
  model_type: Florence-2-large-ft
  load_pretrained: True
  pretrained: 'https://huggingface.co/microsoft/Florence-2-large-ft'


datasets:
  coco_vqa_raw: # name of the dataset builder
    vis_processor:
        eval:
          name: "blip_image_eval"
          image_size: 384
    text_processor:
        eval:
          name: "blip_question"

run:
  task: vqa

  # optimization-specific
  batch_size_train: 32
  batch_size_eval: 32
  num_workers: 4

  # inference-specific
  max_len: 10
  min_len: 1
  num_beams: 5
  num_ans_candidates: 128
  inference_method: "generate"
  prompt: "Question: {} Answer:"

  seed: 42
  output_dir: "output/FLORENCE2/VQA"

  evaluate: True
  train_splits: ["train"]
  valid_splits: ["val"]
  test_splits: ["test"]

  # distribution-specific
  device: "cuda"
  world_size: 8
  dist_url: "env://"
  distributed: True