model:
  arch: blip2_t5_vqa
  model_type: pretrain_flant5xl
  load_pretrained: True
  pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_pretrained_opt6.7b.pth'
  vit_model: eva_clip_g

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"  # "fp32" when freeze_vit is False and "fp16" when freeze_vit is True
  freeze_vit: True

  # Q-Former
  num_query_token: 32

datasets:
  coco_vqa_vs:
    vis_processor:
        train:
          name: "blip_image_train"
          image_size: 224
        eval:
          name: "blip_image_eval"
          image_size: 224
        test:
          name: "blip_image_eval"
          image_size: 224
    text_processor:
        train:
          name: "blip_question"
        eval:
          name: "blip_question"
        test:
          name: "blip_question"
run:
  task: vqa
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5 
  min_lr: 0 
  warmup_steps: 1000
  warmup_lr: 1e-8
  weight_decay: 0.05
  max_epoch: 8
  batch_size_train: 10
  batch_size_eval: 32
  num_workers: 4
  accum_grad_iters: 1
  lr_layer_decay: 0.9 # layer-wise learning rate decay for the ViT 

  max_len: 10
  min_len: 1
  num_beams: 5
  inference_method: "generate"
  prompt: "Question: {} Answer:"

  seed: 42
  output_dir: "output/BLIP2/VQA_VS/t5"

  amp: True
  resume_ckpt_path: null

  evaluate: False
  train_splits: ["train"]
  valid_splits: ["val"]
  test_splits: ["test"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True