datasets:
  domainnet-quickdraw:
    question_type: what-is-in-image
    type: eval
model:
  arch: llava_vqa
  model_type: llava-1.5-7b-hf
  load_finetuned: false
  load_pretrained: true
  lora_rank: 8
  target_modules: q_proj k_proj v_proj o_proj
  use_lora: 1
  wise: 0
run:
  batch_size_eval: 16
  batch_size_train: 16
  device: cuda
  dist_url: env://
  distributed: true
  evaluate: true
  inference_method: generate
  max_len: 10
  min_len: 1
  num_ans_candidates: 128
  num_beams: 5
  num_workers: 4
  output_dir: output/Llava/domainnet-quickdraw
  prompt: 'Question: {} Short answer:'
  seed: 42
  task: classifier_vqa
  test_splits:
    - test
  world_size: 8
