model:
  arch: llava_vqa
  model_type: llava-1.5-7b-hf
  load_pretrained: True
  pretrained: 'https://huggingface.co/llava-hf/llava-1.5-7b-hf'
  load_finetuned: False
  finetuned: '/coc/pskynet4/chuang475/projects/LAVIS/lavis/output/PALIGEMMA/DomainNet-Real/tpcgrad_1e-3_1e-4_mu1e-2_100/20240911152/checkpoint_best.pth'
  # lp: /coc/pskynet4/chuang475/projects/LAVIS/lavis/output/PALIGEMMA/DomainNet-Real/lp_1e-3/20240824012/checkpoint_best.pth

  # lora
  use_lora: 1
  target_modules: "q_proj v_proj"
  lora_rank: 4

  # linear probe
  linear_probe: 0

datasets:
  domainnet-real: # name of the dataset builder
    question_type: what-is-in-image

run:
  task: classifier_vqa
  # optimizer
  opt: "adam"
  proj_term: "both"
  pcgrad_strength: 1.0
  adamh_ortho: False
  adamp_k: 0 # 0.5 1
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-4  # 1e-5 3e-6
  min_lr: 1e-5 # 0
  warmup_steps: 1000
  warmup_lr: 1e-5 # 1e-8 3e-7
  weight_decay: 1e-5 # 3e-7 # 5e-5 0.5 1 1.5 2
  max_epoch: 10
  accum_grad_iters: 2 # 1
  lr_layer_decay: 0.9

  # optimization-specific
  batch_size_train: 6  # 256
  batch_size_eval: 16
  num_workers: 4

  # inference-specific
  max_len: 10
  min_len: 1
  num_beams: 5
  num_ans_candidates: 128
  inference_method: "generate"
  prompt: "Question: {} Short answer:"

  seed: 42
  output_dir: "output/Llava/DomainNet-Real/ft"

  amp: False

  evaluate: False
  train_splits: ["train"]
  valid_splits: ["val"]
  test_splits: ["test"]

  # distribution-specific
  device: "cuda"
  world_size: 8
  dist_url: "env://"
  distributed: True