 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: llava_vqa
  model_type: llava-1.5-7b-hf
  load_pretrained: True
  pretrained: 'https://huggingface.co/llava-hf/llava-1.5-7b-hf'
  load_finetuned: True
  finetuned_lp: /coc/pskynet4/chuang475/projects/LAVIS/lavis/output/Llava/VQA/lp/20241121171/checkpoint_best.pth
  finetuned: /coc/pskynet4/chuang475/projects/LAVIS/lavis/output/Llava/VQA/lpft/20241122212/checkpoint_best.pth
  # /coc/pskynet4/chuang475/projects/LAVIS/lavis/output/Llava/VQA/lpft/20241122212/checkpoint_best.pth
  # /coc/pskynet4/chuang475/projects/LAVIS/lavis/output/Llava/VQA/adamp/20241121170/checkpoint_best.pth
  # /coc/pskynet4/chuang475/projects/LAVIS/lavis/output/Llava/VQA/digrap_0.01/20241122092/checkpoint_best.pth
  # /coc/pskynet4/chuang475/projects/LAVIS/lavis/output/Llava/VQA/adam/20241121114/checkpoint_best.pth

  # lora
  use_lora: 1
  target_modules: "q_proj v_proj"
  lora_rank: 4

  # wise
  wise: 1


datasets:
  coco_iv-vqa: # name of the dataset builder
    vis_processor:
        eval:
          name: "blip_image_eval"
          image_size: 448
    text_processor:
        eval:
          name: "blip_question"

run:
  task: vqa

  # optimization-specific
  batch_size_train: 16
  batch_size_eval: 16
  num_workers: 4

  # inference-specific
  max_len: 10
  min_len: 1
  num_beams: 5
  num_ans_candidates: 128
  inference_method: "generate"
  prompt: "Question: {} Answer:"

  seed: 42
  output_dir: "output/Llava/IV-VQA"

  evaluate: True
  test_splits: ["val"]

  # distribution-specific
  device: "cuda"
  world_size: 8
  dist_url: "env://"
  distributed: True