 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: paligemma_vqa
  model_type: paligemma-3b-pt-224
  load_pretrained: True
  pretrained: 'https://huggingface.co/google/paligemma-3b-pt-224'
  load_finetuned: True
  finetuned: '/coc/pskynet4/chuang475/projects/LAVIS/lavis/output/PALIGEMMA/VQA/adamh/1e-3_wd0.5/20240724145/checkpoint_best.pth'

  # lora
  use_lora: 1
  target_modules: "q_proj k_proj v_proj o_proj"
  lora_rank: 8


datasets:
  coco_cv-vqa: # name of the dataset builder
    vis_processor:
        eval:
          name: "blip_image_eval"
          image_size: 448
    text_processor:
        eval:
          name: "blip_question"

run:
  task: vqa

  # optimization-specific
  batch_size_train: 16
  batch_size_eval: 16
  num_workers: 4

  # inference-specific
  max_len: 10
  min_len: 1
  num_beams: 5
  num_ans_candidates: 128
  inference_method: "generate"
  prompt: "Question: {} Answer:"

  seed: 42
  output_dir: "output/PALIGEMMA/CV-VQA"

  evaluate: True
  test_splits: ["val"]

  # distribution-specific
  device: "cuda"
  world_size: 8
  dist_url: "env://"
  distributed: True