model:
  arch: paligemma_vqa
  model_type: paligemma-3b-pt-224  # paligemma-3b-pt-224
  load_pretrained: True
  pretrained: 'https://huggingface.co/google/paligemma-3b-pt-224'
  load_finetuned: False
  finetuned: '/coc/pskynet4/chuang475/projects/LAVIS/lavis/output/PALIGEMMA/VQA/adamh/l2_1e-3_wd0.5_overcap/20240803000/checkpoint_5.pth'
  # adamp:/coc/pskynet4/chuang475/projects/LAVIS/lavis/output/PALIGEMMA/VQA/20240715010/checkpoint_best.pth'
  # adamh: /coc/pskynet4/chuang475/projects/LAVIS/lavis/output/PALIGEMMA/VQA/20240715010/checkpoint_best.pth'
  # 20240715010, adam: 20240714221
  # 1e-3/20240721224
  # adamh/1e-3_wd0.5/20240724145
  # adamp/1e-3_wd1e-4_new/20240730190
  # linear_probe_1e-3/20240730233

  # lora
  use_lora: 1
  target_modules: "q_proj k_proj v_proj o_proj"
  lora_rank: 8

  # linear probe
  linear_probe: 0

datasets:
  coco_vqa_raw:
    vis_processor:
        train:
          name: "blip_image_train"
          image_size: 224
        eval:
          name: "blip_image_eval"
          image_size: 224
        test:
          name: "blip_image_eval"
          image_size: 224
    text_processor:
        train:
          name: "blip_question"
        eval:
          name: "blip_question"
        test:
          name: "blip_question"

run:
  task: vqa
  # optimizer
  opt: "spcg"
  adamp_k: 0.5 # 0.5 1
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-3  # 1e-5 3e-6
  min_lr: 1e-4 # 0
  warmup_steps: 1000
  warmup_lr: 1e-4 # 1e-8 3e-7
  weight_decay: 1e-1 # 3e-7 # 5e-5 0.5 1 1.5 2
  max_epoch: 10
  accum_grad_iters: 2 # 1
  lr_layer_decay: 0.9

  # optimization-specific
  batch_size_train: 16  # 256
  batch_size_eval: 16
  num_workers: 4

  # inference-specific
  max_len: 10
  min_len: 1
  num_beams: 5
  num_ans_candidates: 128
  inference_method: "generate"
  prompt: "Question: {} Answer:"

  seed: 42
  output_dir: "output/PALIGEMMA/VQA/spcg_1e-3_1e-1"

  amp: False

  evaluate: False
  train_splits: ["train"]
  valid_splits: ["val"]
  test_splits: ["test"]

  # distribution-specific
  device: "cuda"
  world_size: 8
  dist_url: "env://"
  distributed: True