model:
  arch: paligemma_vqa
  model_type: paligemma-3b-pt-224
  load_pretrained: True
  pretrained: 'https://huggingface.co/google/paligemma-3b-pt-224'
  load_finetuned: True
  finetuned: '/coc/pskynet4/chuang475/projects/LAVIS/lavis/output/PALIGEMMA/VQA/1e-3/20240721224/checkpoint_best.pth'
  # adamp:/coc/pskynet4/chuang475/projects/LAVIS/lavis/output/PALIGEMMA/VQA/20240715010/checkpoint_best.pth'
  # adamh: /coc/pskynet4/chuang475/projects/LAVIS/lavis/output/PALIGEMMA/VQA/20240715010/checkpoint_best.pth'
  # 20240715010, adam: 20240714221
  # 1e-3/20240721224

  # lora
  use_lora: 1
  target_modules: "q_proj k_proj v_proj o_proj"
  lora_rank: 8


datasets:
  coco_vqa_raw: # name of the dataset builder
    vis_processor:
        eval:
          name: "blip_image_eval"
          image_size: 384
    text_processor:
        eval:
          name: "blip_question"

run:
  task: vqa

  # optimization-specific
  batch_size_train: 16
  batch_size_eval: 16
  num_workers: 4

  # inference-specific
  max_len: 10
  min_len: 1
  num_beams: 5
  num_ans_candidates: 128
  inference_method: "generate"
  prompt: "Question: {} Answer:"

  seed: 42
  output_dir: "output/PALIGEMMA/VQA"

  evaluate: True
  train_splits: ["train"]
  valid_splits: ["val"]
  test_splits: ["val"]

  # distribution-specific
  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True